// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD67T_jN22VNK0hT2FUBRpuDMh4WyROKt8',
    appId: '1:775878867428:web:94218a5b1639218eaa6ff1',
    messagingSenderId: '775878867428',
    projectId: 'chatting-a4fcd',
    authDomain: 'chatting-a4fcd.firebaseapp.com',
    storageBucket: 'chatting-a4fcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb7lZmVNoCKSdCXZQqHgW7ej7gk25t55Y',
    appId: '1:775878867428:android:0dcc367e524cfb8baa6ff1',
    messagingSenderId: '775878867428',
    projectId: 'chatting-a4fcd',
    storageBucket: 'chatting-a4fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCwiZmzlaP9xZl1covNlI1i88Oho9Zx0',
    appId: '1:775878867428:ios:2bfe61a46c4d3edaaa6ff1',
    messagingSenderId: '775878867428',
    projectId: 'chatting-a4fcd',
    storageBucket: 'chatting-a4fcd.appspot.com',
    iosClientId: '775878867428-29ig71bp9fltb92potmguevq4bv9bqtj.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGCwiZmzlaP9xZl1covNlI1i88Oho9Zx0',
    appId: '1:775878867428:ios:2bfe61a46c4d3edaaa6ff1',
    messagingSenderId: '775878867428',
    projectId: 'chatting-a4fcd',
    storageBucket: 'chatting-a4fcd.appspot.com',
    iosClientId: '775878867428-29ig71bp9fltb92potmguevq4bv9bqtj.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobs',
  );
}
